name: Deploy Reveal.js to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with Git LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Pull LFS content
        run: |
          git lfs install
          git lfs pull

      - name: Create clean publish dir
        run: |
            mkdir public
            shopt -s dotglob extglob nullglob
            cp -r !(public) public/


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
